[package]
name = "gitarena"
version = "0.0.1"
authors = ["Marc Steiner <contact@marcsteiner.me>"]
edition = "2018"
build = "build.rs"
readme = "README.md"
license = "MIT"
repository = "https://github.com/Marc3842h/gitarena"

[dependencies]
actix-rt = "1.1.1"
actix-web = "2.0.0"
anyhow = "1.0.31"
chrono = "0.4.13"
fern = "0.6.0"
git2 = "0.13.8"
gitarena-proc-macro = { version = "0.0.1", path = "gitarena-proc-macro" }
log = "0.4.11"
rand = "0.7.3"
rust-argon2 = { version = "0.8.2", features = ["crossbeam-utils"] }
serde = { version = "1.0.114", features = ["derive"] }
sqlx = { version = "0.3.5", features = ["postgres", "tls"] }
toml = "0.5.6"

[build-dependencies]
config_struct = { version = "0.5.0", features = ["toml-parsing"] }

[workspace]
members = [".", "gitarena-proc-macro"]
