[package]
name = "gitarena"
version = "0.0.1"
authors = ["Marc Steiner <contact@marcsteiner.me>"]
edition = "2018"
readme = "README.md"
license = "MIT"
repository = "https://github.com/Marc3842h/gitarena"

[dependencies]
actix-rt = "1.1.1"
actix-web = "2.0.0"
anyhow = "1.0.31"
chrono = "0.4.13"
fern = "0.6.0"
git2 = "0.13.8"
log = "0.4.11"
sqlx = "0.3.5"
toml = "0.5.6"
