# GitArena config file

bind = "localhost:8080"
domain = "https://gitarena.com"
database = "postgresql://root@localhost/gitarena?sslmode=require"

[hcaptcha]
site_key = ""
secret = ""

[smtp]
server = "smtp.gitarena.com"
port = 465
tls = true
email_address = "noreply@gitarena.com"
username = "root"
password = "hunter2"
