[package]
name = "gitarena-proc-macro"
version = "0.0.1"
authors = ["Marc Steiner <contact@marcsteiner.me>"]
edition = "2018"
readme = "README.md"
license = "MIT"
repository = "https://github.com/Marc3842h/gitarena"
publish = false

[lib]
proc-macro = true
